version: '3'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.1
    container_name: keycloak-container
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: ["start-dev"]
