version: '3'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.1
    container_name: keycloak-container
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: ["start-dev"]

  rabbitmq:
    image: rabbitmq:4.0.2-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/rabbitmq_definitions.json:/etc/rabbitmq/definitions.json:ro

  database:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_DB: pvd-solution
      POSTGRES_PASSWORD: 22I!swq9s
      POSTGRES_USER: sdiv_pred
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - api

networks:
  default:
    driver: bridge

