
server:
  port: ${SERVER_PORT:8090}

spring:

  application:
    name: proposal-management-api

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/proposal-management

  jpa:
    open-in-view: false
    hibernate:
      show_sql: ${DB_JPA_SHOW_SQL:true}
      ddl-auto: ${DB_DDL_AUTO:update}

  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:${DB_PORT:5432}/${DB_DATABASE:proposals_management_db_dev}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    hikari:
      schema: ${DB_SCHEMA:public}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}

  rabbitmq:
    username: ${RABBITMQ_USERNAME:user_queue}
    password: ${RABBITMQ_PASSWORD:user_queue}
    addresses: ${RABBITMQ_ADDRESSES:localhost:5672}
    template:
      queues:
        producers:
          proposal-queue: ${RABBITMQ_PRODUCER_PROPOSAL_QUEUE:proposal_data_queue}
        consumers:
          proposal-update: ${RABBITMQ_CONSUMER_UPDATE_PROPOSAL_QUEUE:proposal_update_queue}