
server:
  port: ${SERVER_PORT:8080}

spring:

  application:
    name: proposal-management-api

  jpa:
    open-in-view: false
    hibernate:
      show_sql: ${DB_JPA_SHOW_SQL}
      ddl-auto: ${DB_DDL_AUTO}

  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      schema: ${DB_SCHEMA}

  flyway:
    enabled: ${FLYWAY_ENABLED}

  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    addresses: ${RABBITMQ_ADDRESSES}
    template:
      queue: ${RABBITMQ_TEMPLATE_QUEUE}
