
server:
  port: ${SERVER_PORT}

spring:

  application:
    name: proposal-management-api

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: ${SPRING_JPA_SHOW_SQL}
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: 1
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: ${DB_SCHEMA}

  flyway:
    enabled: ${FLYWAY_ENABLED}
    schemas: ${DB_SCHEMA}
    baselineOnMigrate: true
