
server:
  port: ${SERVER_PORT:8080}

spring:

  application:
    name: proposal-management-api

  jpa:
    open-in-view: false
    hibernate:
      show_sql: ${DB_JPA_SHOW_SQL:true}
      ddl-auto: ${DB_DDL_AUTO:update}

  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:${DB_PORT:5432}/${DB_DATABASE:proposals_management_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    hikari:
      schema: ${DB_SCHEMA:public}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
