
server:
  port: ${SERVER_PORT}

spring:

  application:
    name: proposal-processor-api

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      queue: ${RABBITMQ_TEMPLATE_QUEUE}
