
server:
  port: ${SERVER_PORT}

spring:

  application:
    name: proposal-processor-api

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: ${SPRING_JPA_SHOW_SQL}
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: 1
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: ${DB_SCHEMA}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      queue: ${RABBITMQ_TEMPLATE_QUEUE}
