
server:
  port: 8090

spring:

  application:
    name: proposal-processor-api

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:user_queue}
    password: ${RABBITMQ_PASSWORD:user_queue}
    template:
      queue: ${RABBITMQ_TEMPLATE_QUEUE:proposal_data_queue}