
server:
  port: ${SERVER_PORT}

spring:

  application:
    name: proposal-processor-api

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      queues:
        producers:
          proposal-management: ${RABBITMQ_PRODUCER_MANAGEMENT}
        consumers:
          proposal-management: ${RABBITMQ_CONSUMER_MANAGEMENT}
